import Nav from '../component/nav';
import Footer from '../component/Footer'
import './globals.css'
import UserContext from './context/UserContext';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserContext>
        <Nav/>
        <main className="main container">
          {children}
        </main>
        <Footer/>
        </UserContext>
      </body>
    </html>
  );
}