import Nav from '../component/nav';
import './globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav/>
        <main className="main container">
          {children}
        </main>
      </body>
    </html>
  );
}